sudo: false

language: node_js
node_js:
  - "4"
  - "5"
  - "6"
  - "7"
  - "8"

before_script:
  - node --version
  - npm --version
  - npm install -g gulp

script:
  - npm test

after_script:
  - gulp coveralls

matrix:
  fast_finish: true
